bedtools getfasta -fi /users/jaspenc/reference/hg38.fa -bed /users/jaspenc/project2/ENCFF087SET.bed -fo output1.txt
bedtools getfasta -fi /users/jaspenc/reference/hg38.fa -bed /users/jaspenc/project2/ENCFF100BSX.bed -fo output2.txt
bedtools getfasta -fi /users/jaspenc/reference/hg38.fa -bed /users/jaspenc/project2/ENCFF193WPS.bed -fo output3.txt
bedtools getfasta -fi /users/jaspenc/reference/hg38.fa -bed /users/jaspenc/project2/ENCFF197BBD.bed -fo output4.txt
bedtools getfasta -fi /users/jaspenc/reference/hg38.fa -bed /users/jaspenc/project2/ENCFF202SHK.bed -fo output5.txt
bedtools getfasta -fi /users/jaspenc/reference/hg38.fa -bed /users/jaspenc/project2/ENCFF260PVK.bed -fo output6.txt
bedtools getfasta -fi /users/jaspenc/reference/hg38.fa -bed /users/jaspenc/project2/ENCFF419XZN.bed -fo output7.txt
bedtools getfasta -fi /users/jaspenc/reference/hg38.fa -bed /users/jaspenc/project2/ENCFF424KQR.bed -fo output8.txt
bedtools getfasta -fi /users/jaspenc/reference/hg38.fa -bed /users/jaspenc/project2/ENCFF459MDW.bed -fo output9.txt
bedtools getfasta -fi /users/jaspenc/reference/hg38.fa -bed /users/jaspenc/project2/ENCFF783FEB.bed -fo output10.txt
